# Generated by Django 6.0.3 on 2026-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactionlog',
            name='reference_type',
            field=models.CharField(choices=[('deposit_request', 'Deposit request'), ('withdrawal_request', 'Withdrawal request'), ('order', 'Order')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wallettransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase')], max_length=20),
        ),
    ]
