# Generated by Codex on 2026-04-03

import secrets
import uuid

from django.db import migrations, models
from django.utils import timezone


def populate_order_access_fields(apps, schema_editor):
    Order = apps.get_model("marketplace", "Order")
    for order in Order.objects.all():
        if not order.order_number:
            order.order_number = f"LD-{timezone.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
        order.is_guest = order.user_id is None
        if order.is_guest and not order.guest_access_token:
            order.guest_access_token = secrets.token_urlsafe(32)
            order.guest_token_created_at = timezone.now()
        if not order.is_guest:
            order.guest_access_token = None
            order.guest_token_created_at = None
            order.guest_token_expires_at = None
        order.save(
            update_fields=[
                "order_number",
                "is_guest",
                "guest_access_token",
                "guest_token_created_at",
                "guest_token_expires_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_alter_wallettransactionlog_reference_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_access_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(
            code=populate_order_access_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="order",
            name="guest_access_token",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
