# Generated by Codex on 2026-04-03

from decimal import Decimal

from django.db import migrations, models


def backfill_deposit_usd_fields(apps, schema_editor):
    DepositRequest = apps.get_model("marketplace", "DepositRequest")
    PaymentAsset = apps.get_model("marketplace", "PaymentAsset")

    for deposit in DepositRequest.objects.select_related("crypto_asset").all():
        if not deposit.asset_amount:
            deposit.asset_amount = deposit.amount
        if not deposit.credited_amount_usd:
            deposit.credited_amount_usd = deposit.amount
        if deposit.payment_asset_id is None and deposit.crypto_asset_id:
            payment_asset = (
                PaymentAsset.objects.filter(
                    symbol=deposit.crypto_asset.symbol,
                    network=deposit.crypto_asset.network,
                    wallet_address=deposit.crypto_asset.wallet_address,
                ).first()
            )
            if payment_asset:
                deposit.payment_asset_id = payment_asset.id
                if payment_asset.usd_rate and payment_asset.usd_rate > 0:
                    deposit.credited_amount_usd = deposit.asset_amount * payment_asset.usd_rate
        deposit.save(update_fields=["asset_amount", "credited_amount_usd", "payment_asset"])


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_order_access_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentasset",
            name="usd_rate",
            field=models.DecimalField(decimal_places=6, default=Decimal("1.000000"), max_digits=14),
        ),
        migrations.AddField(
            model_name="depositrequest",
            name="asset_amount",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="depositrequest",
            name="credited_amount_usd",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="depositrequest",
            name="payment_asset",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name="deposit_requests", to="marketplace.paymentasset"),
        ),
        migrations.AlterField(
            model_name="depositrequest",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.RunPython(
            code=backfill_deposit_usd_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
