# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_payment_asset_deposits_usd"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportContactSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_channel", models.CharField(default="@liliyuan111", max_length=120)),
                ("whatsapp_number", models.CharField(default="+66 91 817 1423", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Support contact settings",
            },
        ),
    ]
